In [1]:
import numpy as np
from timecave.validation_methods.prequential import Rolling_Window, Growing_Window
from timecave.validation_methods.CV import Block_CV

In [2]:
ts = np.arange(19277);

In [3]:
ts.shape[0]

19277

In [4]:
roll = Rolling_Window(5, ts, 1);

In [5]:
roll.info()

Rolling Window method
---------------------
Time series size: 19277 samples
Number of splits: 5
Fold size: 3855 to 3856 samples (20.0 to 20.0 %)
Gap: 0
Weights: [1. 1. 1. 1.]


In [6]:
roll.n_splits

5

In [7]:
roll._splitting_ind

array([    0,  3856,  7712, 11567, 15422, 19277])

In [8]:
for it, (train, test, w) in enumerate(roll.split()):

    print(f"Iteration {it+1}");

Iteration 1
Iteration 2
Iteration 3
Iteration 4


In [9]:
new_ts = np.ones(9);

In [10]:
roll_new_ts = Rolling_Window(5, new_ts, 1);

In [11]:
roll_new_ts._splitting_ind

array([0, 2, 4, 6, 8, 9])

In [12]:
for it, (train, test, w) in enumerate(roll_new_ts.split()):

    print("Train: ", train);
    print("Validation: ", test);
    print(f"Iteration {it+1}");

Train:  [0 1]
Validation:  [2 3]
Iteration 1
Train:  [2 3]
Validation:  [4 5]
Iteration 2
Train:  [4 5]
Validation:  [6 7]
Iteration 3
Train:  [6 7]
Validation:  [8]
Iteration 4


In [13]:
ts_simple = np.ones(16);

In [14]:
roll_simple = Rolling_Window(5, ts_simple, 1);

In [15]:
roll_simple._splitting_ind

array([ 0,  4,  7, 10, 13, 16])

In [16]:
for it, (train, test, w) in enumerate(roll_simple.split()):

    print(f"Iteration {it+1}");

Iteration 1
Iteration 2
Iteration 3
Iteration 4


In [17]:
gap_roll = Rolling_Window(5, ts, 1, gap=1);

In [18]:
gap_roll._splitting_ind

array([    0,  3856,  7712, 11567, 15422, 19277])

In [19]:
for it, (train, test, w) in enumerate(gap_roll.split()):

    print(f"Iteration {it+1}");

Iteration 1
Iteration 2
Iteration 3


In [20]:
gap_roll_simple = Rolling_Window(5, ts_simple, 1, gap=2);

In [21]:
gap_roll_simple._splitting_ind

array([ 0,  4,  7, 10, 13, 16])

In [22]:
for it, (train, test, w) in enumerate(gap_roll_simple.split()):

    print("Train: ", train);
    print("Validation: ", test);
    print(f"Iteration {it+1}");

Train:  [0 1 2 3]
Validation:  [10 11 12]
Iteration 1
Train:  [4 5 6]
Validation:  [13 14 15]
Iteration 2


### Growing window

In [23]:
grow = Growing_Window(5, ts, 1);

In [24]:
grow._splitting_ind

array([ 3856,  7712, 11567, 15422, 19277])

In [25]:
for it, (train, test, w) in enumerate(grow.split()):

    print(f"Iteration {it+1}");

Iteration 1
Iteration 2
Iteration 3
Iteration 4


In [26]:
grow_simple = Growing_Window(5, ts_simple, 1);

In [27]:
grow_simple._splitting_ind

array([ 4,  7, 10, 13, 16])

In [28]:
for it, (train, test, w) in enumerate(grow_simple.split()):

    print("Train: ", train);
    print("Validation: ", test);
    print(f"Iteration {it+1}");

Train:  [0 1 2 3]
Validation:  [4 5 6]
Iteration 1
Train:  [0 1 2 3 4 5 6]
Validation:  [7 8 9]
Iteration 2
Train:  [0 1 2 3 4 5 6 7 8 9]
Validation:  [10 11 12]
Iteration 3
Train:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12]
Validation:  [13 14 15]
Iteration 4


In [29]:
new_grow = Growing_Window(5, new_ts, 1);

In [30]:
new_grow._splitting_ind

array([2, 4, 6, 8, 9])

In [31]:
for it, (train, test, w) in enumerate(new_grow.split()):

    print("Train: ", train);
    print("Validation: ", test);
    print(f"Iteration {it+1}");

Train:  [0 1]
Validation:  [2 3]
Iteration 1
Train:  [0 1 2 3]
Validation:  [4 5]
Iteration 2
Train:  [0 1 2 3 4 5]
Validation:  [6 7]
Iteration 3
Train:  [0 1 2 3 4 5 6 7]
Validation:  [8]
Iteration 4


### Block CV

In [32]:
block = Block_CV(5, ts, 1);

In [33]:
block._splitting_ind

array([    0,  3856,  7712, 11567, 15422, 19277])

In [34]:
for it, (train, test, w) in enumerate(block.split()):

    print(f"Iteration {it+1}");

Iteration 1
Iteration 2
Iteration 3
Iteration 4
Iteration 5


In [35]:
block_simple = Block_CV(5, ts_simple, 1);

In [36]:
block_simple._splitting_ind

array([ 0,  4,  7, 10, 13, 16])

In [37]:
for it, (train, test, w) in enumerate(block_simple.split()):

    print(f"Iteration {it+1}");

Iteration 1
Iteration 2
Iteration 3
Iteration 4
Iteration 5


In [38]:
new_block = Block_CV(5, new_ts, 1);

In [39]:
new_block._splitting_ind

array([0, 2, 4, 6, 8, 9])

In [40]:
for it, (train, test, w) in enumerate(new_block.split()):

    print(f"Iteration {it+1}");

Iteration 1
Iteration 2
Iteration 3
Iteration 4
Iteration 5
