In [7]:
import numpy as np
from timecave.validation_methods.prequential import Rolling_Window, Growing_Window

In [2]:
np.floor(19277 / 5)

3855.0

In [3]:
int(np.floor(19277 % 5))

2

In [4]:
3855 * 5 + 2

19277

In [5]:
ts = np.arange(19277);

In [6]:
ts.shape[0]

19277

In [8]:
roll = Rolling_Window(5, ts, 1);

In [9]:
roll.info()

Rolling Window method
---------------------
Time series size: 19277 samples
Number of splits: 5
Fold size: 3855 to 3856 samples (20.0 to 20.0 %)
Gap: 0
Weights: [1. 1. 1. 1.]


In [10]:
roll.n_splits

5

In [11]:
roll._splitting_ind

array([    0,  3856,  7712, 11567, 15422])

In [12]:
for it, (train, test, w) in enumerate(roll.split()):

    print(f"Iteration {it+1}");

Iteration 1
Iteration 2
Iteration 3


In [148]:
new_ts = np.ones(12);

In [149]:
roll_new_ts = Rolling_Window(5, new_ts, 1);

In [150]:
roll_new_ts._splitting_ind

array([ 0,  3,  6,  8, 10])

In [151]:
exp = [np.round(i/5 * 12) for i in range(6)];

In [152]:
exp

[0.0, 2.0, 5.0, 7.0, 10.0, 12.0]

In [153]:
for it, (train, test, w) in enumerate(roll_new_ts.split()):

    print("Train: ", train);
    print("Validation: ", test);
    print(f"Iteration {it+1}");

Train:  [0 1 2]
Validation:  [3 4 5]
Iteration 1
Train:  [3 4 5]
Validation:  [6 7]
Iteration 2
Train:  [6 7]
Validation:  [8 9]
Iteration 3


In [115]:
int(8 % 5)

3

In [117]:
int(np.floor(8 / 5))

1

In [118]:
np.arange(0, 8, 1)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
ts_simple = np.ones(15);

In [14]:
roll_simple = Rolling_Window(5, ts_simple, 1);

In [15]:
for it, (train, test, w) in enumerate(roll_simple.split()):

    print(f"Iteration {it+1}");

Iteration 1
Iteration 2
Iteration 3
Iteration 4


In [17]:
roll_simple._splitting_ind

array([ 0,  3,  6,  9, 12, 15])

### Growing window