In [1]:
import numpy as np
from timecave.validation_methods.prequential import Rolling_Window, Growing_Window
from timecave.validation_methods.CV import Block_CV

In [2]:
ts = np.arange(19277);

In [3]:
ts.shape[0]

19277

In [4]:
roll = Rolling_Window(5, ts, 1);

In [5]:
roll.info()

Rolling Window method
---------------------
Time series size: 19277 samples
Number of splits: 5
Fold size: 3855 to 3856 samples (20.0 to 20.0 %)
Gap: 0
Weights: [1. 1. 1. 1.]


In [6]:
roll.n_splits

5

In [7]:
roll._splitting_ind

array([    0,  3856,  7712, 11567, 15422])

In [8]:
for it, (train, test, w) in enumerate(roll.split()):

    print(f"Iteration {it+1}");

Iteration 1
Iteration 2
Iteration 3


In [12]:
new_ts = np.ones(8);

In [13]:
roll_new_ts = Rolling_Window(5, new_ts, 1);

In [14]:
roll_new_ts._splitting_ind

array([0, 2, 4, 6, 7, 8, 9])

In [15]:
exp = [np.round(i/5 * 12) for i in range(6)];

In [16]:
exp

[0.0, 2.0, 5.0, 7.0, 10.0, 12.0]

In [17]:
for it, (train, test, w) in enumerate(roll_new_ts.split()):

    print("Train: ", train);
    print("Validation: ", test);
    print(f"Iteration {it+1}");

Train:  [0 1]
Validation:  [2 3]
Iteration 1
Train:  [2 3]
Validation:  [4 5]
Iteration 2
Train:  [4 5]
Validation:  [6]
Iteration 3
Train:  [6]
Validation:  [7]
Iteration 4


In [21]:
ts_simple = np.ones(17);

In [22]:
roll_simple = Rolling_Window(5, ts_simple, 1);

In [23]:
roll_simple._splitting_ind

array([ 0,  4,  8, 11, 14])

In [24]:
for it, (train, test, w) in enumerate(roll_simple.split()):

    print(f"Iteration {it+1}");

Iteration 1
Iteration 2
Iteration 3


### Growing window

In [25]:
grow = Growing_Window(5, ts, 1);

In [26]:
grow._splitting_ind

array([ 3856,  7712, 11567, 15422, 19277])

In [27]:
for it, (train, test, w) in enumerate(grow.split()):

    print(f"Iteration {it+1}");

Iteration 1
Iteration 2
Iteration 3
Iteration 4


In [28]:
grow_simple = Growing_Window(5, ts_simple, 1);

In [29]:
grow_simple._splitting_ind

array([ 3,  6,  9, 12, 15])

In [30]:
for it, (train, test, w) in enumerate(grow_simple.split()):

    print("Train: ", train);
    print("Validation: ", test);
    print(f"Iteration {it+1}");

Train:  [0 1 2]
Validation:  [3 4 5]
Iteration 1
Train:  [0 1 2 3 4 5]
Validation:  [6 7 8]
Iteration 2
Train:  [0 1 2 3 4 5 6 7 8]
Validation:  [ 9 10 11]
Iteration 3
Train:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Validation:  [12 13 14]
Iteration 4


In [31]:
new_grow = Growing_Window(5, new_ts, 1);

In [32]:
new_grow._splitting_ind

array([2, 4, 6, 7, 8, 9])

In [33]:
for it, (train, test, w) in enumerate(new_grow.split()):

    print("Train: ", train);
    print("Validation: ", test);
    print(f"Iteration {it+1}");

Train:  [0 1]
Validation:  [2 3]
Iteration 1
Train:  [0 1 2 3]
Validation:  [4 5]
Iteration 2
Train:  [0 1 2 3 4 5]
Validation:  [6]
Iteration 3
Train:  [0 1 2 3 4 5 6]
Validation:  [7]
Iteration 4


### Block CV

In [34]:
block = Block_CV(5, ts, 1);

In [35]:
block._splitting_ind

array([    0,  3856,  7712, 11567, 15422, 19277])

In [36]:
for it, (train, test, w) in enumerate(block.split()):

    print(f"Iteration {it+1}");

Iteration 1
Iteration 2
Iteration 3
Iteration 4
Iteration 5


In [37]:
block_simple = Block_CV(5, ts_simple, 1);

In [38]:
block_simple._splitting_ind

array([ 0,  3,  6,  9, 12, 15])

In [39]:
for it, (train, test, w) in enumerate(block_simple.split()):

    print(f"Iteration {it+1}");

Iteration 1
Iteration 2
Iteration 3
Iteration 4
Iteration 5


In [40]:
new_block = Block_CV(5, new_ts, 1);

In [41]:
new_block._splitting_ind

array([ 0,  2,  4,  6,  7,  8,  9, 10])

In [42]:
for it, (train, test, w) in enumerate(new_block.split()):

    print(f"Iteration {it+1}");

Iteration 1
Iteration 2
Iteration 3
Iteration 4
Iteration 5
